-- Phase 2 initial migration.
--
-- HAND-WRITTEN, not generated by `prisma migrate dev`.
-- `binaries.prisma.sh` (Prisma's engine-binary CDN) is not in this agent's
-- allowed egress domains (confirmed via `prisma validate`/`generate`/
-- `migrate dev`/`format` all failing identically with 403 on that host,
-- including with PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1). No Prisma CLI
-- command could run. This file was derived by hand from
-- apps/api/prisma/schema.prisma and applied directly via `psql` against a
-- real local Postgres instance, then verified with introspection queries
-- (see AGENT_HANDOFF.md for the exact verification performed).
--
-- IMPORTANT for the next agent with binary access: run `prisma migrate dev`
-- against a FRESH database first, to let Prisma generate its own canonical
-- version of this migration and confirm it matches what's below (diff the
-- two). If they match (or differ only in constraint-naming style, not
-- substance), mark this migration as applied on any DB that already has it
-- via `prisma migrate resolve --applied 20260828060000_init` rather than
-- re-running it. If they don't match in substance, that's a bug in this
-- hand-written file to fix, not a schema.prisma problem.

-- ============================================================================
-- Enums
-- ============================================================================

CREATE TYPE "UserRole" AS ENUM ('student', 'professor', 'researcher', 'club_rep', 'startup_member', 'alumni', 'admin');
CREATE TYPE "UserStatus" AS ENUM ('pending_verification', 'active', 'suspended', 'banned');
CREATE TYPE "VerificationRoleClaim" AS ENUM ('professor', 'researcher', 'club_rep', 'startup_member', 'admin');
CREATE TYPE "VerificationStatus" AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE "ResearcherType" AS ENUM ('phd', 'postdoc', 'research_associate', 'research_assistant', 'faculty');
CREATE TYPE "Visibility" AS ENUM ('public', 'university_only', 'connections_only', 'private');
CREATE TYPE "OrganizationType" AS ENUM ('club', 'society', 'startup');
CREATE TYPE "MembershipRole" AS ENUM ('member', 'leader', 'advisor', 'founder', 'pi');
CREATE TYPE "ProjectStatus" AS ENUM ('idea', 'planning', 'development', 'beta', 'active', 'completed', 'archived');
CREATE TYPE "SkillRoleNeeded" AS ENUM ('frontend', 'backend', 'ml', 'design', 'research', 'product', 'other');
CREATE TYPE "SkillProficiency" AS ENUM ('beginner', 'intermediate', 'advanced', 'expert');
CREATE TYPE "EventType" AS ENUM ('hackathon', 'workshop', 'seminar', 'conference', 'talk', 'guest_lecture', 'competition', 'startup_event', 'club_event');
CREATE TYPE "OpportunityType" AS ENUM ('research', 'internship', 'project', 'startup', 'volunteer', 'club', 'hackathon', 'mentorship', 'thesis', 'research_assistant', 'teaching_assistant');
CREATE TYPE "ApplicationStatus" AS ENUM ('submitted', 'under_review', 'accepted', 'rejected');
CREATE TYPE "ConnectionStatus" AS ENUM ('pending', 'accepted', 'declined', 'blocked');
CREATE TYPE "ConversationType" AS ENUM ('direct', 'group', 'project', 'research_team', 'club');
CREATE TYPE "InvitationType" AS ENUM ('none', 'project', 'research_team');
CREATE TYPE "NotificationType" AS ENUM ('connection_request', 'new_message', 'project_invitation', 'research_invitation', 'club_announcement', 'event_reminder', 'opportunity_deadline', 'new_publication', 'team_recruitment', 'profile_interaction');
CREATE TYPE "ReportTargetType" AS ENUM ('user', 'project', 'organization', 'publication', 'message');
CREATE TYPE "ReportReason" AS ENUM ('fake_account', 'spam', 'harassment', 'impersonation', 'misleading', 'inappropriate');
CREATE TYPE "ReportStatus" AS ENUM ('open', 'reviewing', 'resolved', 'dismissed');
CREATE TYPE "ReportAction" AS ENUM ('none', 'restrict', 'suspend', 'ban');

-- ============================================================================
-- Core Identity
-- ============================================================================

CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "phone" TEXT,
    "password_hash" TEXT NOT NULL,
    "requested_role" "UserRole" NOT NULL,
    "status" "UserStatus" NOT NULL DEFAULT 'pending_verification',
    "is_university_verified" BOOLEAN NOT NULL DEFAULT false,
    "university_domain" TEXT,
    "avatar_url" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");
CREATE INDEX "users_status_idx" ON "users"("status");

CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "revoked_at" TIMESTAMP(3),
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

CREATE TABLE "verifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "role_claimed" "VerificationRoleClaim" NOT NULL,
    "status" "VerificationStatus" NOT NULL DEFAULT 'pending',
    "reviewed_by" UUID,
    "evidence_url" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "verifications_user_id_role_claimed_key" ON "verifications"("user_id", "role_claimed");
CREATE INDEX "verifications_user_id_idx" ON "verifications"("user_id");
CREATE INDEX "verifications_reviewed_by_idx" ON "verifications"("reviewed_by");

-- ============================================================================
-- Profiles
-- ============================================================================

CREATE TABLE "student_profiles" (
    "user_id" UUID NOT NULL,
    "full_name" TEXT NOT NULL,
    "department" TEXT,
    "course" TEXT,
    "year" INTEGER,
    "university" TEXT,
    "bio" TEXT,
    "cgpa" DECIMAL(3,2),
    "github_url" TEXT,
    "linkedin_url" TEXT,
    "portfolio_url" TEXT,
    "looking_for" JSONB,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "student_profiles_pkey" PRIMARY KEY ("user_id")
);

CREATE TABLE "professor_profiles" (
    "user_id" UUID NOT NULL,
    "full_name" TEXT NOT NULL,
    "department" TEXT,
    "designation" TEXT,
    "expertise" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "bio" TEXT,
    "office_contact" TEXT,
    "mentorship_available" BOOLEAN NOT NULL DEFAULT false,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "professor_profiles_pkey" PRIMARY KEY ("user_id")
);

CREATE TABLE "researcher_profiles" (
    "user_id" UUID NOT NULL,
    "full_name" TEXT NOT NULL,
    "researcher_type" "ResearcherType" NOT NULL,
    "department" TEXT,
    "bio" TEXT,
    "current_availability" BOOLEAN NOT NULL DEFAULT true,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "researcher_profiles_pkey" PRIMARY KEY ("user_id")
);

CREATE TABLE "privacy_settings" (
    "user_id" UUID NOT NULL,
    "profile_visibility" "Visibility" NOT NULL DEFAULT 'university_only',
    "email_visibility" "Visibility" NOT NULL DEFAULT 'connections_only',
    "phone_visibility" "Visibility" NOT NULL DEFAULT 'connections_only',
    "academic_visibility" "Visibility" NOT NULL DEFAULT 'university_only',
    "cgpa_visibility" "Visibility" NOT NULL DEFAULT 'private',
    "projects_visibility" "Visibility" NOT NULL DEFAULT 'public',
    "research_visibility" "Visibility" NOT NULL DEFAULT 'public',
    "social_links_visibility" "Visibility" NOT NULL DEFAULT 'university_only',
    "connections_visibility" "Visibility" NOT NULL DEFAULT 'connections_only',
    "activity_visibility" "Visibility" NOT NULL DEFAULT 'connections_only',
    "contact_visibility" "Visibility" NOT NULL DEFAULT 'connections_only',
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "privacy_settings_pkey" PRIMARY KEY ("user_id")
);

-- ============================================================================
-- Organizations
-- ============================================================================

CREATE TABLE "organizations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" "OrganizationType" NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logo_url" TEXT,
    "description" TEXT,
    "category" TEXT,
    "faculty_advisor_id" UUID,
    "created_by" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations"("slug");
CREATE INDEX "organizations_faculty_advisor_id_idx" ON "organizations"("faculty_advisor_id");
CREATE INDEX "organizations_created_by_idx" ON "organizations"("created_by");

CREATE TABLE "startup_details" (
    "organization_id" UUID NOT NULL,
    "industry" TEXT,
    "stage" TEXT,
    "website_url" TEXT,
    "hiring" BOOLEAN NOT NULL DEFAULT false,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "startup_details_pkey" PRIMARY KEY ("organization_id")
);

CREATE TABLE "memberships" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "organization_id" UUID,
    "research_team_id" UUID,
    "role" "MembershipRole" NOT NULL DEFAULT 'member',
    "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "memberships_user_id_idx" ON "memberships"("user_id");
CREATE INDEX "memberships_organization_id_idx" ON "memberships"("organization_id");
CREATE INDEX "memberships_research_team_id_idx" ON "memberships"("research_team_id");

-- ============================================================================
-- Research
-- ============================================================================

CREATE TABLE "research_topics" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "parent_topic_id" UUID,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "research_topics_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "research_topics_name_key" ON "research_topics"("name");
CREATE UNIQUE INDEX "research_topics_slug_key" ON "research_topics"("slug");
CREATE INDEX "research_topics_parent_topic_id_idx" ON "research_topics"("parent_topic_id");

CREATE TABLE "research_teams" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "pi_user_id" UUID NOT NULL,
    "created_by" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "research_teams_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "research_teams_pi_user_id_idx" ON "research_teams"("pi_user_id");
CREATE INDEX "research_teams_created_by_idx" ON "research_teams"("created_by");

CREATE TABLE "research_team_topics" (
    "research_team_id" UUID NOT NULL,
    "research_topic_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "research_team_topics_pkey" PRIMARY KEY ("research_team_id", "research_topic_id")
);
CREATE INDEX "research_team_topics_research_team_id_idx" ON "research_team_topics"("research_team_id");
CREATE INDEX "research_team_topics_research_topic_id_idx" ON "research_team_topics"("research_topic_id");

-- Added per DECISIONS.md D-009.
CREATE TABLE "user_research_topics" (
    "user_id" UUID NOT NULL,
    "research_topic_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "user_research_topics_pkey" PRIMARY KEY ("user_id", "research_topic_id")
);
CREATE INDEX "user_research_topics_user_id_idx" ON "user_research_topics"("user_id");
CREATE INDEX "user_research_topics_research_topic_id_idx" ON "user_research_topics"("research_topic_id");

CREATE TABLE "publications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "abstract" TEXT,
    "journal_or_conference" TEXT,
    "published_date" DATE,
    "doi" TEXT,
    "external_url" TEXT,
    "pdf_url" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "publications_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "publication_authors" (
    "publication_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "author_order" INTEGER NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "publication_authors_pkey" PRIMARY KEY ("publication_id", "user_id")
);
CREATE INDEX "publication_authors_publication_id_idx" ON "publication_authors"("publication_id");
CREATE INDEX "publication_authors_user_id_idx" ON "publication_authors"("user_id");

CREATE TABLE "publication_topics" (
    "publication_id" UUID NOT NULL,
    "research_topic_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "publication_topics_pkey" PRIMARY KEY ("publication_id", "research_topic_id")
);
CREATE INDEX "publication_topics_publication_id_idx" ON "publication_topics"("publication_id");
CREATE INDEX "publication_topics_research_topic_id_idx" ON "publication_topics"("research_topic_id");

-- ============================================================================
-- Projects
-- ============================================================================

CREATE TABLE "projects" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "logo_url" TEXT,
    "problem_statement" TEXT,
    "solution_description" TEXT,
    "description" TEXT,
    "status" "ProjectStatus" NOT NULL DEFAULT 'idea',
    "github_url" TEXT,
    "demo_url" TEXT,
    "docs_url" TEXT,
    "created_by" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "projects_created_by_idx" ON "projects"("created_by");

CREATE TABLE "project_members" (
    "project_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role_on_project" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "project_members_pkey" PRIMARY KEY ("project_id", "user_id")
);
CREATE INDEX "project_members_project_id_idx" ON "project_members"("project_id");
CREATE INDEX "project_members_user_id_idx" ON "project_members"("user_id");

CREATE TABLE "skills" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "category" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "skills_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "skills_name_key" ON "skills"("name");

CREATE TABLE "project_skills_needed" (
    "project_id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "role_needed" "SkillRoleNeeded" NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "project_skills_needed_pkey" PRIMARY KEY ("project_id", "skill_id", "role_needed")
);
CREATE INDEX "project_skills_needed_project_id_idx" ON "project_skills_needed"("project_id");
CREATE INDEX "project_skills_needed_skill_id_idx" ON "project_skills_needed"("skill_id");

CREATE TABLE "project_topics" (
    "project_id" UUID NOT NULL,
    "research_topic_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "project_topics_pkey" PRIMARY KEY ("project_id", "research_topic_id")
);
CREATE INDEX "project_topics_project_id_idx" ON "project_topics"("project_id");
CREATE INDEX "project_topics_research_topic_id_idx" ON "project_topics"("research_topic_id");

CREATE TABLE "user_skills" (
    "user_id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "proficiency" "SkillProficiency",
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "user_skills_pkey" PRIMARY KEY ("user_id", "skill_id")
);
CREATE INDEX "user_skills_user_id_idx" ON "user_skills"("user_id");
CREATE INDEX "user_skills_skill_id_idx" ON "user_skills"("skill_id");

-- ============================================================================
-- Events
-- ============================================================================

CREATE TABLE "events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "event_type" "EventType" NOT NULL,
    "date" DATE NOT NULL,
    "time" TIME,
    "venue" TEXT,
    "organizer_organization_id" UUID,
    "organizer_research_team_id" UUID,
    "registration_url" TEXT,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "events_organizer_organization_id_idx" ON "events"("organizer_organization_id");
CREATE INDEX "events_organizer_research_team_id_idx" ON "events"("organizer_research_team_id");

CREATE TABLE "event_participants" (
    "event_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "event_participants_pkey" PRIMARY KEY ("event_id", "user_id")
);
CREATE INDEX "event_participants_event_id_idx" ON "event_participants"("event_id");
CREATE INDEX "event_participants_user_id_idx" ON "event_participants"("user_id");

-- ============================================================================
-- Opportunities
-- ============================================================================

CREATE TABLE "opportunities" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "opportunity_type" "OpportunityType" NOT NULL,
    "provided_by_organization_id" UUID,
    "provided_by_research_team_id" UUID,
    "deadline" DATE,
    "department_tag" TEXT,
    "research_topic_id" UUID,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "opportunities_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "opportunities_provided_by_organization_id_idx" ON "opportunities"("provided_by_organization_id");
CREATE INDEX "opportunities_provided_by_research_team_id_idx" ON "opportunities"("provided_by_research_team_id");
CREATE INDEX "opportunities_research_topic_id_idx" ON "opportunities"("research_topic_id");

CREATE TABLE "applications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "opportunity_id" UUID NOT NULL,
    "applicant_id" UUID NOT NULL,
    "status" "ApplicationStatus" NOT NULL DEFAULT 'submitted',
    "submitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "applications_opportunity_id_idx" ON "applications"("opportunity_id");
CREATE INDEX "applications_applicant_id_idx" ON "applications"("applicant_id");

-- ============================================================================
-- Networking
-- ============================================================================

CREATE TABLE "connections" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "requester_id" UUID NOT NULL,
    "addressee_id" UUID NOT NULL,
    "status" "ConnectionStatus" NOT NULL DEFAULT 'pending',
    "message" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "connections_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "connections_requester_id_addressee_id_key" ON "connections"("requester_id", "addressee_id");
CREATE INDEX "connections_requester_id_idx" ON "connections"("requester_id");
CREATE INDEX "connections_addressee_id_idx" ON "connections"("addressee_id");

CREATE TABLE "follows" (
    "follower_id" UUID NOT NULL,
    "followee_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "follows_pkey" PRIMARY KEY ("follower_id", "followee_id")
);
CREATE INDEX "follows_follower_id_idx" ON "follows"("follower_id");
CREATE INDEX "follows_followee_id_idx" ON "follows"("followee_id");

-- ============================================================================
-- Messaging
-- ============================================================================

CREATE TABLE "conversations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" "ConversationType" NOT NULL,
    "project_id" UUID,
    "research_team_id" UUID,
    "organization_id" UUID,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "conversations_project_id_idx" ON "conversations"("project_id");
CREATE INDEX "conversations_research_team_id_idx" ON "conversations"("research_team_id");
CREATE INDEX "conversations_organization_id_idx" ON "conversations"("organization_id");

CREATE TABLE "conversation_participants" (
    "conversation_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("conversation_id", "user_id")
);
CREATE INDEX "conversation_participants_conversation_id_idx" ON "conversation_participants"("conversation_id");
CREATE INDEX "conversation_participants_user_id_idx" ON "conversation_participants"("user_id");

CREATE TABLE "messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "conversation_id" UUID NOT NULL,
    "sender_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "attachment_url" TEXT,
    "invitation_type" "InvitationType",
    "invitation_ref_id" UUID,
    "sent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "messages_conversation_id_idx" ON "messages"("conversation_id");
CREATE INDEX "messages_sender_id_idx" ON "messages"("sender_id");

-- ============================================================================
-- Notifications
-- ============================================================================

CREATE TABLE "notifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" "NotificationType" NOT NULL,
    "payload" JSONB NOT NULL,
    "read_at" TIMESTAMP(3),
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "notifications_user_id_idx" ON "notifications"("user_id");

CREATE TABLE "notification_preferences" (
    "user_id" UUID NOT NULL,
    "connection_requests" BOOLEAN NOT NULL DEFAULT true,
    "messages" BOOLEAN NOT NULL DEFAULT true,
    "project_invitations" BOOLEAN NOT NULL DEFAULT true,
    "research_invitations" BOOLEAN NOT NULL DEFAULT true,
    "club_announcements" BOOLEAN NOT NULL DEFAULT true,
    "event_reminders" BOOLEAN NOT NULL DEFAULT true,
    "opportunity_deadlines" BOOLEAN NOT NULL DEFAULT true,
    "publications" BOOLEAN NOT NULL DEFAULT true,
    "team_recruitment" BOOLEAN NOT NULL DEFAULT true,
    "profile_interactions" BOOLEAN NOT NULL DEFAULT true,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("user_id")
);

-- ============================================================================
-- Moderation
-- ============================================================================

CREATE TABLE "reports" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "reporter_id" UUID NOT NULL,
    "target_type" "ReportTargetType" NOT NULL,
    "target_id" UUID NOT NULL,
    "reason" "ReportReason" NOT NULL,
    "description" TEXT,
    "status" "ReportStatus" NOT NULL DEFAULT 'open',
    "reviewed_by" UUID,
    "action" "ReportAction",
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reports_reporter_id_idx" ON "reports"("reporter_id");
CREATE INDEX "reports_reviewed_by_idx" ON "reports"("reviewed_by");
CREATE INDEX "reports_target_type_target_id_idx" ON "reports"("target_type", "target_id");

-- ============================================================================
-- Foreign Keys
-- ============================================================================

ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "verifications" ADD CONSTRAINT "verifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "verifications" ADD CONSTRAINT "verifications_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "student_profiles" ADD CONSTRAINT "student_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "professor_profiles" ADD CONSTRAINT "professor_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "researcher_profiles" ADD CONSTRAINT "researcher_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "privacy_settings" ADD CONSTRAINT "privacy_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "organizations" ADD CONSTRAINT "organizations_faculty_advisor_id_fkey" FOREIGN KEY ("faculty_advisor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "startup_details" ADD CONSTRAINT "startup_details_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_research_team_id_fkey" FOREIGN KEY ("research_team_id") REFERENCES "research_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
-- Constraint from DATABASE_SCHEMA.md: "exactly one of organization_id/research_team_id non-null".
-- No native Prisma schema syntax for this — see schema.prisma Membership comment.
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_exactly_one_parent_check" CHECK (
    (("organization_id" IS NOT NULL)::int + ("research_team_id" IS NOT NULL)::int) = 1
);

ALTER TABLE "research_topics" ADD CONSTRAINT "research_topics_parent_topic_id_fkey" FOREIGN KEY ("parent_topic_id") REFERENCES "research_topics"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "research_teams" ADD CONSTRAINT "research_teams_pi_user_id_fkey" FOREIGN KEY ("pi_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "research_teams" ADD CONSTRAINT "research_teams_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "research_team_topics" ADD CONSTRAINT "research_team_topics_research_team_id_fkey" FOREIGN KEY ("research_team_id") REFERENCES "research_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "research_team_topics" ADD CONSTRAINT "research_team_topics_research_topic_id_fkey" FOREIGN KEY ("research_topic_id") REFERENCES "research_topics"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_research_topics" ADD CONSTRAINT "user_research_topics_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_research_topics" ADD CONSTRAINT "user_research_topics_research_topic_id_fkey" FOREIGN KEY ("research_topic_id") REFERENCES "research_topics"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "publication_authors" ADD CONSTRAINT "publication_authors_publication_id_fkey" FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "publication_authors" ADD CONSTRAINT "publication_authors_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "publication_topics" ADD CONSTRAINT "publication_topics_publication_id_fkey" FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "publication_topics" ADD CONSTRAINT "publication_topics_research_topic_id_fkey" FOREIGN KEY ("research_topic_id") REFERENCES "research_topics"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "projects" ADD CONSTRAINT "projects_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "project_members" ADD CONSTRAINT "project_members_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "project_skills_needed" ADD CONSTRAINT "project_skills_needed_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_skills_needed" ADD CONSTRAINT "project_skills_needed_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "project_topics" ADD CONSTRAINT "project_topics_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "project_topics" ADD CONSTRAINT "project_topics_research_topic_id_fkey" FOREIGN KEY ("research_topic_id") REFERENCES "research_topics"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_skills" ADD CONSTRAINT "user_skills_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_skills" ADD CONSTRAINT "user_skills_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "events" ADD CONSTRAINT "events_organizer_organization_id_fkey" FOREIGN KEY ("organizer_organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "events" ADD CONSTRAINT "events_organizer_research_team_id_fkey" FOREIGN KEY ("organizer_research_team_id") REFERENCES "research_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "event_participants" ADD CONSTRAINT "event_participants_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "event_participants" ADD CONSTRAINT "event_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_provided_by_organization_id_fkey" FOREIGN KEY ("provided_by_organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_provided_by_research_team_id_fkey" FOREIGN KEY ("provided_by_research_team_id") REFERENCES "research_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_research_topic_id_fkey" FOREIGN KEY ("research_topic_id") REFERENCES "research_topics"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "applications" ADD CONSTRAINT "applications_opportunity_id_fkey" FOREIGN KEY ("opportunity_id") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "connections" ADD CONSTRAINT "connections_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "connections" ADD CONSTRAINT "connections_addressee_id_fkey" FOREIGN KEY ("addressee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "follows" ADD CONSTRAINT "follows_followee_id_fkey" FOREIGN KEY ("followee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "conversations" ADD CONSTRAINT "conversations_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_research_team_id_fkey" FOREIGN KEY ("research_team_id") REFERENCES "research_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "reports" ADD CONSTRAINT "reports_reporter_id_fkey" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reports" ADD CONSTRAINT "reports_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- Full-text search: generated tsvector columns + GIN indexes.
-- Per DATABASE_SCHEMA.md "Indexing Summary". Represented in schema.prisma as
-- `Unsupported("tsvector")` fields (Prisma has no generated-column syntax),
-- so `prisma migrate dev`'s drift detection knows about them and won't try
-- to drop them. Phase 5 (search) queries these with $queryRaw.
-- ============================================================================

-- Postgres's built-in array_to_string() is STABLE, not IMMUTABLE, so it
-- cannot be used directly inside a GENERATED ALWAYS AS ... STORED expression
-- (discovered when applying this migration: professor_profiles' column
-- failed with "generation expression is not immutable" while the otherwise
-- identical student_profiles one succeeded, since only professor_profiles'
-- expression touches an array column). Standard, well-documented Postgres
-- workaround: a thin SQL wrapper explicitly marked IMMUTABLE — safe here
-- because array_to_string has no actual non-deterministic behavior of its
-- own; the STABLE label is a conservative default Postgres applies to it.
CREATE OR REPLACE FUNCTION "immutable_array_to_string"(text[], text) RETURNS text AS $$
    SELECT array_to_string($1, $2);
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

ALTER TABLE "student_profiles" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce("bio", ''))) STORED;
CREATE INDEX "student_profiles_search_vector_idx" ON "student_profiles" USING GIN ("search_vector");

ALTER TABLE "professor_profiles" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("bio", '') || ' ' || "immutable_array_to_string"("expertise", ' '))
    ) STORED;
CREATE INDEX "professor_profiles_search_vector_idx" ON "professor_profiles" USING GIN ("search_vector");

ALTER TABLE "researcher_profiles" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce("bio", ''))) STORED;
CREATE INDEX "researcher_profiles_search_vector_idx" ON "researcher_profiles" USING GIN ("search_vector");

ALTER TABLE "projects" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("name", '') || ' ' || coalesce("description", ''))
    ) STORED;
CREATE INDEX "projects_search_vector_idx" ON "projects" USING GIN ("search_vector");

ALTER TABLE "publications" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("title", '') || ' ' || coalesce("abstract", ''))
    ) STORED;
CREATE INDEX "publications_search_vector_idx" ON "publications" USING GIN ("search_vector");

ALTER TABLE "organizations" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("name", '') || ' ' || coalesce("description", ''))
    ) STORED;
CREATE INDEX "organizations_search_vector_idx" ON "organizations" USING GIN ("search_vector");

ALTER TABLE "research_topics" ADD COLUMN "search_vector" tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("name", '') || ' ' || coalesce("description", ''))
    ) STORED;
CREATE INDEX "research_topics_search_vector_idx" ON "research_topics" USING GIN ("search_vector");
